#!/usr/bin/env bash
## Usage: cloudflare-ufw
## UFW firewall setup for Cloudflare proxied websites. 

## Remove old backups
rm /etc/ufw/{after,after6,before,before6,user,user6}.rules.*

## UFW reset rules
ufw --force reset

## UFW allow LIMITed SSH access
ufw limit ssh

## UFW Whitelist Cloudflare IPs https://www.cloudflare.com/ips/
for ip in $(curl -s https://www.cloudflare.com/ips-v{4,6}); do ufw allow from ${ip} to any port 80,443 proto tcp; done
## UFW Whitelist UptimeRobot IPs (Fix CRLF/LF) https://uptimerobot.com/locations
for ip in $(curl -s https://uptimerobot.com/inc/files/ips/IPv4andIPv6.txt | tr -d '\r'); do ufw allow from ${ip} to any port 80,443 proto tcp; done

## ENABLE UFW Firewall
ufw --force enable
