#!/bin/bash
## EASYENGINE.IO Server prep v4 BETA

## Defaults to avoid prompt during ee install
echo "[user]" > /root/.gitconfig
echo "name = Hosting Co." >> /root/.gitconfig
echo "email = webmaster@example.com" >> /root/.gitconfig

## Set AWS Credentials
mkdir /root/.aws
echo "[default]" > /root/.aws/config
echo "aws_access_key_id=XXXXXXXXXXXXXXX" >> /root/.aws/config
echo "aws_secret_access_key=YYYYYYYYYYYYYYYYYYYYYYYYYYYYY" >> /root/.aws/config

## Update Ubuntu 18.04
export DEBIAN_FRONTEND=noninteractive
export DEBIAN_PRIORITY=critical
sudo -E apt-get -qy update
sudo -E apt-get -qy -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" upgrade
sudo -E apt-get -qy autoclean

## Install AWS CLI
apt-get install -y python-pip
pip install awscli

## Install EasyEngine.io v4
wget -qO ee rt.cx/ee4 && sudo bash ee  

## All websites require CloudFlare proxy ufw firewall setup
wget -qO /etc/cron.weekly/cloudflare-ufw https://raw.githubusercontent.com/microram/ee4-tools/master/cloudflare-ufw && chmod +x /etc/cron.weekly/cloudflare-ufw && sudo bash /etc/cron.weekly cloudflare-ufw 

## Get the site settings file
aws s3 cp s3://bucketname/scripts/.backup_sites_mysql_s3.conf /root/
chmod 400 /root/.backup_sites_mysql_s3.conf
if [[ -r /root/.backup_sites_mysql_s3.conf ]] ; then
    . /root/.backup_sites_mysql_s3.conf
else
    echo "ERROR - Settings file not found or not readable."
	#; exit 1
fi


wget https://raw.githubusercontent.com/microram/ee4-tools/master/cloudflare-ufw.sh && sudo bash cloudflare-ufw.sh 

## Get the site deploy script
#aws s3 cp s3://$bucket/scripts/ee4-restore-site.sh ~/
#chmod +x ee4-restore-site.sh

## Get the backup scripts and settings
#aws s3 cp s3://$bucket/scripts/backup_sites_s3 /etc/cron.daily/
#chmod +x /etc/cron.daily/backup_sites_s3
#aws s3 cp s3://$bucket/scripts/backup_mysql_s3 /etc/cron.daily/
#chmod +x /etc/cron.daily/backup_mysql_s3

## Get the list of sites to restore
#restorefile=`aws s3 ls s3://$bucket/$config_base_folder/restorelist/ | awk '{print $4}' | tail -1`
#aws s3 cp s3://$bucket/$config_base_folder/restorelist/$restorefile ~/
#chmod +x ~/$restorefile*

## Get the latest LetsEncrypt certs
#lefile=`aws s3 ls s3://$bucket/$le_base_folder/ | awk '{print $4}' | tail -1`
#aws s3 cp s3://$bucket/$le_base_folder/$lefile $tmp
#tar xf $tmp/$lefile* -C /etc/letsencrypt/

## Finished
#echo "Ready to restore the sites. Run the restorelist next."
## Check for reboot after ee install

if [[ -f /var/run/reboot-required ]]
then 
	echo "Reboot required before continuing. Please restart this script after reboot."
	reboot
fi
