#!/usr/bin/env bash
## Usage: ee4-setup-server
## Ubuntu 18.04 - EasyEngine v4 - WordPress hosting server init script

## Defaults to avoid prompt during ee install
echo "[user]" > /root/.gitconfig
echo "name = Hosting Co." >> /root/.gitconfig
echo "email = webmaster@example.com" >> /root/.gitconfig

## Set AWS Credentials
mkdir /root/.aws
echo "[default]" > /root/.aws/config
echo "aws_access_key_id=XXXXXXXXXXXXXXX" >> /root/.aws/config
echo "aws_secret_access_key=YYYYYYYYYYYYYYYYYYYYYYYYYYYYY" >> /root/.aws/config

## Set the GPG Keys
## TODO

## No editing below this line needed
## ---------------------------------

## Update Ubuntu
export DEBIAN_FRONTEND=noninteractive
export DEBIAN_PRIORITY=critical
sudo -E apt-get -qy update
sudo -E apt-get -qy -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" upgrade
sudo -E apt-get -qy autoclean

## Install AWS CLI
apt-get install -y python-pip
pip install awscli

## Install EasyEngine.io v4
wget -qO ee rt.cx/ee4 && sudo bash ee

## UFW firewall setup. All websites require CloudFlare proxy
wget -qO /etc/cron.weekly/cloudflare-ufw https://raw.githubusercontent.com/microram/ee4-tools/master/cloudflare-ufw && chmod +x /etc/cron.weekly/cloudflare-ufw && sudo bash /etc/cron.weekly/cloudflare-ufw

## Get the site settings file
wget -qO /root/.ee4-backup-settings.conf https://raw.githubusercontent.com/microram/ee4-tools/master/.ee4-backup-settings.conf && chmod 600 /root/.ee4-backup-settings.conf

## Get the backup script. Place in /etc/cron.daily/ and ln in root
wget -qO /etc/cron.daily/ee4-backup-sites https://raw.githubusercontent.com/microram/ee4-tools/master/ee4-backup-sites && chmod +x /etc/cron.daily/ee4-backup-sites && ln -s /etc/cron.daily/ee4-backup-sites /root/ee4-backup-sites

## Get the restore script. Place in /root
wget -qO /root/ee4-restore-site https://raw.githubusercontent.com/microram/ee4-tools/master/ee4-restore-site && chmod +x /root/ee4-restore-site

## Get the v3 restore script. Place in /root
wget -qO /root/ee4-restore-from-v3-site https://raw.githubusercontent.com/microram/ee4-tools/master/ee4-restore-from-v3-site && chmod +x /root/ee4-restore-from-v3-site

## Fix up the settings file
## TODO

## Get the newest restorelist
## TODO

## Check for reboot after ee install
if [[ -f /var/run/reboot-required ]]
then 
	echo "Reboot required before continuing. Please restart this script after reboot."
	reboot
fi
